import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,readFileSync,writeFileSync,mkdirSync} from 'node:fs';import {resolve} from 'node:path';import {spawnSync} from 'node:child_process';
import {pathToFileURL} from 'node:url';
const script=resolve('scripts/fetchArchive.ts');const mock=pathToFileURL(resolve('tests/mock-x.mjs')).href;
function fixture(){mkdirSync('.state/test-runs',{recursive:true});const dir=mkdtempSync(resolve('.state/test-runs/run-'));writeFileSync(`${dir}/archive.config.json`,JSON.stringify({username:'mihina_48',includeReplies:false,source:'full-archive',pageSize:10,postReadUSD:.005,userReadUSD:.01}));return dir;}
function run(dir:string,args:string[]=[],extra:Record<string,string>={}){const result=spawnSync(process.execPath,['--import',mock,script,...args],{cwd:dir,env:{...process.env,X_BEARER_TOKEN:'FAKE_TEST_ONLY',X_APPROVE_PAID:'true',X_MAX_COST_USD:'1',...extra},encoding:'utf8'});if(result.status!==0&&args.includes('--update'))console.error(result.stderr);return result;}
const read=(dir:string,path:string)=>JSON.parse(readFileSync(`${dir}/${path}`,'utf8'));
test('pagination, interrupted resume, watermark update and repeat-run deduplication',()=>{const dir=fixture();const first=run(dir,[],{FIXTURE_FAIL:'true'});assert.equal(first.status,1,first.stderr);assert.match(first.stderr,/rate limit/);assert.equal(read(dir,'.state/full.json').pages,1);assert.equal(read(dir,'.state/full.json').token,'p2');const resumed=run(dir);assert.equal(resumed.status,0,resumed.stderr);const full=read(dir,'.state/full.json');assert.equal(full.pages,3);assert.equal(full.complete,true);assert.equal(full.newestId,'300');assert.equal(read(dir,'public/data/archive.json').length,3);const before=readFileSync(`${dir}/requests.jsonl`,'utf8');assert.equal(run(dir).status,0);assert.equal(readFileSync(`${dir}/requests.jsonl`,'utf8'),before);assert.equal(run(dir,['--update']).status,0);assert.equal(read(dir,'public/data/archive.json').length,4);assert.equal(read(dir,'.state/update.json').sinceId,'300');assert.equal(run(dir,['--update']).status,0);assert.equal(read(dir,'public/data/archive.json').length,4);});
test('missing credential and absent payment approval make zero requests',()=>{const dir=fixture();assert.match(run(dir,[],{X_BEARER_TOKEN:''}).stderr,/credential missing/);assert.match(run(dir,[],{X_APPROVE_PAID:'false'}).stderr,/Paid access is locked/);assert.throws(()=>readFileSync(`${dir}/requests.jsonl`));});
test('cost budget stops before next page and reservations survive restarts',()=>{const dir=fixture();const result=run(dir,[],{X_MAX_COST_USD:'0.06'});assert.equal(result.status,1);assert.match(result.stderr,/budget exhausted/);assert.equal(read(dir,'.state/full.json').pages,1);assert.equal(read(dir,'.state/full.json').reservedUSD,.06);assert.equal(run(dir,[],{X_MAX_COST_USD:'0.06'}).status,1);assert.equal(readFileSync(`${dir}/requests.jsonl`,'utf8').trim().split('\n').length,2);});
test('interrupted update resumes the same watermark without double-counting scanned posts',()=>{const dir=fixture();assert.equal(run(dir).status,0);const first=run(dir,['--update'],{FIXTURE_UPDATE_PAGES:'true',FIXTURE_FAIL:'true'});assert.equal(first.status,1);assert.equal(read(dir,'public/data/archive-meta.json').completed,false);assert.equal(read(dir,'public/data/archive-meta.json').total_posts_scanned,4);const resumed=run(dir,['--update'],{FIXTURE_UPDATE_PAGES:'true'});assert.equal(resumed.status,0,resumed.stderr);assert.equal(read(dir,'.state/update.json').sinceId,'300');assert.equal(read(dir,'public/data/archive-meta.json').total_posts_scanned,5);assert.equal(read(dir,'public/data/archive.json').length,5);});
