import React, {useEffect,useMemo,useRef,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {filterPosts,parseArchive,MetaSchema,months,type Post,type Meta,type Photo} from './archive';
import './style.css';

const dateLabel=(s:string)=>new Date(s).toLocaleDateString('en-US',{day:'2-digit',month:'long',year:'numeric',timeZone:'UTC'});
function Photograph({photo,eager=false}:{photo:Photo;eager?:boolean}){
 const [failed,setFailed]=useState(false);
 return failed?<div className="unavailable" style={{aspectRatio:`${photo.width}/${photo.height}`}}><span>Image unavailable</span><small>The original may have been removed.</small></div>:<img src={photo.url} width={photo.width} height={photo.height} alt={photo.alt_text||'Photograph from the archive'} loading={eager?'eager':'lazy'} decoding="async" onError={()=>setFailed(true)}/>;
}
function Text({post}:{post:Post}){const chars=Array.from(post.text);const nodes:React.ReactNode[]=[];let cursor=0;for(const e of [...(post.entities||[])].sort((a,b)=>a.start-b.start)){if(e.start<cursor)continue;nodes.push(chars.slice(cursor,e.start).join(''));nodes.push(<a key={e.start} href={e.url} target="_blank" rel="noreferrer">{e.label}</a>);cursor=e.end;}nodes.push(chars.slice(cursor).join(''));return <p className="post-text">{nodes}</p>}
function Attribution({post,meta}:{post:Post;meta:Meta}){return <div className="attribution"><a className="author" href={`https://x.com/${meta.username}`} target="_blank" rel="noreferrer">{meta.profile_image_url&&<img src={meta.profile_image_url} alt=""/>}<span><strong>{meta.display_name}</strong><small>@{meta.username}</small></span></a><span aria-label="Source: X">𝕏</span><Text post={post}/><div className="post-links"><a href={post.post_url} target="_blank" rel="noreferrer">{dateLabel(post.created_at)}{post.edited?' · Edited':''}</a><a href={post.post_url} target="_blank" rel="noreferrer">View on X ↗</a></div></div>}
function Viewer({posts,initial,meta,onClose}:{posts:Post[];initial:{id:string;photo:number};meta:Meta;onClose:()=>void}){
 const frames=useMemo(()=>posts.flatMap(p=>p.photos.map((photo,i)=>({post:p,photo,index:i}))),[posts]);
 const [index,setIndex]=useState(()=>Math.max(0,frames.findIndex(f=>f.post.post_id===initial.id&&f.index===initial.photo)));
 const dialog=useRef<HTMLDialogElement>(null);const frame=frames[index];
 useEffect(()=>{const el=dialog.current!;el.showModal();const saved=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.body.style.overflow=saved;el.close();}},[]);
 function move(delta:number){setIndex(i=>Math.min(frames.length-1,Math.max(0,i+delta)))}
 return <dialog ref={dialog} className="viewer" aria-label="Photograph detail" onCancel={onClose} onClick={e=>{if(e.target===e.currentTarget)onClose()}} onKeyDown={e=>{if(e.key==='ArrowRight'){e.preventDefault();move(1)}if(e.key==='ArrowLeft'){e.preventDefault();move(-1)}}}><div className="viewer-shell"><header><span>{meta.demo?'DEMO COLLECTION':'VISUAL ARCHIVE'} <span className="muted">/ {String(index+1).padStart(2,'0')}</span></span><button onClick={onClose} aria-label="Close photograph">Close <span>×</span></button></header><div className="viewer-body"><div className="viewer-image"><Photograph key={frame.photo.media_key} photo={frame.photo} eager/></div><aside><span className="eyebrow">{dateLabel(frame.post.created_at)}</span><h2>{meta.demo?'A moment, held.':`@${meta.username}`}</h2>{meta.demo?<><p>{frame.post.text}</p><p className="muted">Sample photography. This is not a post by @{meta.username}.</p></>:<Attribution post={frame.post} meta={meta}/>}<div className="photo-count">Photo {frame.index+1} <span>of {frame.post.photos.length}</span></div><div className="thumbnails">{frame.post.photos.map((p,i)=><button aria-label={`Show photo ${i+1}`} aria-pressed={i===frame.index} key={p.media_key} onClick={()=>setIndex(frames.findIndex(f=>f.post.post_id===frame.post.post_id&&f.index===i))}><Photograph photo={p}/></button>)}</div><a className="original-link" href={meta.demo?frame.photo.source_url:frame.post.post_url} target="_blank" rel="noreferrer">{meta.demo?'View demo image source':'View original post'} ↗</a>{meta.demo&&<small className="muted">{frame.photo.credit}</small>}<div className="viewer-navigation"><button onClick={()=>move(-1)} disabled={index===0} aria-label="Previous photograph">← Previous</button><button onClick={()=>move(1)} disabled={index===frames.length-1} aria-label="Next photograph">Next →</button></div><small className="keyboard-hint">← → to explore &nbsp; · &nbsp; ESC to close</small></aside></div></div></dialog>
}
function App(){
 const [posts,setPosts]=useState<Post[]>([]),[meta,setMeta]=useState<Meta|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true);
 const [year,setYear]=useState(''),[month,setMonth]=useState(''),[type,setType]=useState(''),[search,setSearch]=useState(''),[order,setOrder]=useState('newest'),[stats,setStats]=useState(false),[viewer,setViewer]=useState<{id:string;photo:number}|null>(null);
 const [activeYear,setActiveYear]=useState('');
 useEffect(()=>{const c=new AbortController();Promise.all(['/data/archive.json','/data/archive-meta.json'].map(async url=>{const r=await fetch(url,{signal:c.signal});if(!r.ok)throw new Error('Archive unavailable');return r.json()})).then(([a,m])=>{const records=parseArchive(a);const metadata=MetaSchema.parse(m);if(metadata.total_photo_posts!==records.length||metadata.total_photos!==records.reduce((n,p)=>n+p.photos.length,0))throw new Error('Archive totals do not match');setPosts(records);setMeta(metadata)}).catch(e=>{if(e.name!=='AbortError')setError('The archive could not be loaded. Its data may be unavailable or incomplete. Please try again later.')}).finally(()=>setLoading(false));return()=>c.abort()},[]);
 const years=useMemo(()=>[...new Set(posts.map(p=>p.created_at.slice(0,4)))].sort().reverse(),[posts]);
 const filtered=useMemo(()=>filterPosts(posts,{year,month,type,search,order}),[posts,year,month,type,search,order]);
 const groups=useMemo(()=>{const map=new Map<string,Post[]>();for(const p of filtered){const key=p.created_at.slice(0,7);map.set(key,[...(map.get(key)||[]),p])}return [...map.entries()]},[filtered]);
 useEffect(()=>{const observer=new IntersectionObserver(entries=>{const entry=entries.find(e=>e.isIntersecting);if(entry)setActiveYear(entry.target.getAttribute('data-year')||'')},{rootMargin:'-100px 0px -65% 0px'});document.querySelectorAll('[data-year]').forEach(el=>observer.observe(el));return()=>observer.disconnect()},[groups]);
 const countPhotos=filtered.reduce((n,p)=>n+p.photos.length,0);
 function reset(){setYear('');setMonth('');setType('');setSearch('');setOrder('newest')}
 function jump(y:string){if(year&&year!==y)setYear('');setTimeout(()=>{const el=document.getElementById(`year-${y}`);if(el){el.scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'start'});setActiveYear(y)}},0)}
 const hasFilters=!!(year||month||type||search);
 return <><a className="skip-link" href="#collection">Skip to photographs</a><header className="masthead"><a href="#" className="wordmark" onClick={reset}><span className="archive-mark" aria-hidden="true">▥</span>X VISUAL ARCHIVE</a><nav aria-label="Main navigation"><a href="#collection">Collection</a><button aria-expanded={stats} onClick={()=>setStats(s=>!s)}>Archive index <span>↗</span></button></nav></header><main><section className="intro"><div><p className="eyebrow">A PHOTOGRAPHIC RECORD <span className="tiny-line"/></p><h1>Through the years<span className="period">.</span></h1><div className="intro-caption"><a href="https://x.com/mihina_48" target="_blank" rel="noreferrer">@mihina_48 ↗</a><span className="caption-rule"/><span>Collected moments, in chronological order.</span></div></div><div className="intro-meta"><span className="eyebrow">COLLECTION SPAN</span><div className="date-range">{years.length?`${years.at(-1)} — ${years[0]}`:'—'}</div><span className="muted">{meta?.demo?'Demo edition · September 2026':meta?.last_synced?`Updated ${dateLabel(meta.last_synced)}`:'Awaiting archive'}</span></div></section>
 {meta?.demo&&<div className="demo-notice"><span className="demo-label">DEMO EDITION</span><span>Sample images for exploring the archive. Not photographs by @mihina_48.</span><a href="#about">About this collection ↗</a></div>}
 <section className="collection" id="collection"><aside className="timeline"><div className="eyebrow">CHRONOLOGY</div><button className={!year&&!activeYear?'selected':''} onClick={()=>{reset();window.scrollTo({top:0,behavior:'smooth'})}}>All years <span>{posts.length}</span></button>{years.map(y=><button className={(activeYear===y||year===y)?'selected':''} key={y} onClick={()=>jump(y)}>{y}<span>{posts.filter(p=>p.created_at.startsWith(y)).length}</span></button>)}<div className="sidebar-note"><span className="eyebrow">IN THE ARCHIVE</span><strong>{meta?.total_photos||'0'}</strong><span>photographs</span><small>Across {posts.length} posts<br/>and {years.length} years.</small></div></aside><div className="collection-content"><div className="toolbar"><div className="tabs"><button className={!type?'active':''} onClick={()=>setType('')}>All photographs</button><button className={type==='single'?'active':''} onClick={()=>setType('single')}>Single photo</button><button className={type==='multiple'?'active':''} onClick={()=>setType('multiple')}>Multiple photos</button></div><label className="search"><span aria-hidden="true">⌕</span><input aria-label="Search archive" type="search" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search the archive"/></label></div><div className="filter-row"><div><label><span className="sr-only">Year</span><select aria-label="Year" value={year} onChange={e=>setYear(e.target.value)}><option value="">All years</option>{years.map(y=><option key={y}>{y}</option>)}</select></label><label><span className="sr-only">Month</span><select aria-label="Month" value={month} onChange={e=>setMonth(e.target.value)}><option value="">All months</option>{months.map((m,i)=><option value={String(i)} key={m}>{m}</option>)}</select></label>{hasFilters&&<button className="reset" onClick={reset}>Reset ×</button>}</div><label><span className="sr-only">Sort order</span><select aria-label="Sort order" value={order} onChange={e=>setOrder(e.target.value)}><option value="newest">Newest first</option><option value="oldest">Oldest first</option></select></label></div>
 {stats&&<section className="statistics" aria-label="Archive statistics"><div className="stat-numbers"><div><strong>{posts.length}</strong><span>PHOTO POSTS</span></div><div><strong>{meta?.total_photos||0}</strong><span>PHOTOGRAPHS</span></div><div><strong>{years.length}</strong><span>YEARS</span></div></div><div className="stat-chart">{years.map(y=>{const n=posts.filter(p=>p.created_at.startsWith(y)).length;return <button key={y} onClick={()=>{setYear(y);setStats(false)}}><span>{y}</span><i style={{width:`${n/Math.max(...years.map(yy=>posts.filter(p=>p.created_at.startsWith(yy)).length))*100}%`}}/><span>{n}</span></button>})}</div></section>}
 <div aria-live="polite" className="results-count">{loading?'Opening the archive…':`${filtered.length} posts · ${countPhotos} photographs`}{hasFilters&&' · Filtered collection'}</div>
 {error?<div className="empty" role="alert"><span>ARCHIVE UNAVAILABLE</span><h2>A pause in the collection.</h2><p>{error}</p><button onClick={()=>location.reload()}>Try again ↗</button></div>:!loading&&!filtered.length?<div className="empty"><span>NO PHOTOGRAPHS FOUND</span><h2>{posts.length?'A different way of looking.':'The collection begins here.'}</h2><p>{posts.length?'Try another month, year, or search term.':'No accessible photo posts have been imported yet.'}</p>{posts.length>0&&<button onClick={reset}>Clear filters ↗</button>}</div>:groups.map(([key,items],gi)=>{const y=key.slice(0,4);const first=gi===0||groups[gi-1][0].slice(0,4)!==y;return <section className="month-section" key={key} data-year={y} id={first?`year-${y}`:undefined}>{first&&<div className="year-heading"><h2>{y}</h2><span>{filtered.filter(p=>p.created_at.startsWith(y)).length} POSTS IN THIS YEAR</span></div>}<div className="month-heading"><h3>{months[Number(key.slice(5))-1]}</h3><span>{String(Number(key.slice(5))).padStart(2,'0')} / {y}</span><div/><span>{items.reduce((n,p)=>n+p.photos.length,0)} photographs</span></div><div className="photo-grid">{items.map((post,pi)=><article className="photo-card" key={post.post_id}><button className="photo-button" aria-label={`Open photographs from ${dateLabel(post.created_at)}`} onClick={()=>setViewer({id:post.post_id,photo:0})}><Photograph photo={post.photos[0]} eager={gi===0&&pi<3}/><span className="image-overlay"><span>{dateLabel(post.created_at)}</span><span>Open ↗</span></span>{post.photos.length>1&&<span className="stack-badge">▱ {post.photos.length}</span>}</button><div className="card-caption"><span>{new Date(post.created_at).toLocaleDateString('en-GB',{day:'2-digit',month:'short',timeZone:'UTC'})}</span><span>{post.photos.length>1?`${post.photos.length} photographs`:'Single photograph'}<span className="caption-arrow"> ↗</span></span></div>{!meta?.demo&&meta&&<Attribution post={post} meta={meta}/>}</article>)}</div></section>})}
 </div></section><footer id="about"><div><a href="#" className="wordmark">X VISUAL ARCHIVE</a><p>An independent visual record for @mihina_48.<br/>Not affiliated with or endorsed by X or the account owner.</p>{meta?.demo&&<p>Demo photography via <a href="https://picsum.photos" target="_blank" rel="noreferrer">Lorem Picsum</a> / <a href="https://unsplash.com/license" target="_blank" rel="noreferrer">Unsplash</a>. Sample dates and captions are fictional.</p>}</div><div><span className="eyebrow">ABOUT THE ARCHIVE</span><p>{meta?.coverage||'No archive loaded.'}</p><p>Photographs remain with their original hosts.<br/>Browse by year. Open a moment. Find its source.</p><a href="#">Back to top ↑</a></div></footer></main>{viewer&&meta&&<Viewer posts={filtered} initial={viewer} meta={meta} onClose={()=>setViewer(null)}/>}</>
}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>);
